apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: 1.0
    spec:
      containers:
        - name: demo-container
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8080
